% Mass Transfer Computation in a two phase countercurrent flow.
% Distillation at the microscale level.
% Jaime Ortiz. October, 2008

% This script was developed under COMSOL 3.4 and COMSOL script (discontinued).
% It may need to be modified to run on MatLab and a newer COMSOL version.
   

flclear fem

% Parameterized 2D channel geometry

width=320e-6;                   %Microchannel width
depth=110e-6;                   %Microchannel height
xi=0.25; 			%The value of xi is based on area

total_area=( width - 2 * depth ) * depth + pi * depth^2 / 2;
liquid_area = total_area * xi;

% Interface centre of curvature

curvature_x_coordinate = depth / 2;
curvature_y_coordinate = width - depth - ( liquid_area -( pi * depth^2 ) / 4 + ( pi * ( depth / 2 )^2) / 2) /depth;

% Geometry description
g1 = rect2(depth,depth,'base','corner','pos',{'0','0'},'rot','0');
g2 = circ2(depth,'base','center','pos',[depth,depth],'rot','0');
g3 = geomcomp({g1,g2},'ns',{'g1','g2'},'sf','g1*g2','edge','none');
g4 = rect2(depth,curvature_y_coordinate-depth,'base','corner','pos',[0,depth],'rot','0');
g6 = geomcomp({g3,g4},'ns',{'g3','g4'},'sf','g3+g4','edge','none');
g7 = geomdel(g6);
g8 = circ2(depth/2,'base','center','pos',[curvature_x_coordinate,curvature_y_coordinate],'rot','0');
g9 = geomcomp({g7,g8},'ns',{'g7','g8'},'sf','g7+g8','edge','none');
g10 = geomdel(g9);
g11 = rect2(depth,width-depth-curvature_y_coordinate,'base','corner','pos',[0,curvature_y_coordinate],'rot','0');
g12 = geomcomp({g10,g11},'ns',{'g10','g11'},'sf','g10+g11','edge','none');
garr = split(g12);
[ g13, g14, g15, g16, g17 ] = deal( garr{ : } );
g18 = geomcomp({g13,g15,g16},'ns',{'g13','g15','g16'},'sf','g13+g15+g16','edge','none');
g19 = geomdel(g18);
g20 = rect2(depth,depth,'base','corner','pos',[0,width-depth],'rot','0');
g21 = circ2(depth,'base','center','pos',[depth,width-depth],'rot','0');
g22 = geomcomp({g20,g21},'ns',{'g20','g21'},'sf','g20*g21','edge','none');
g24 = circ2(depth/2,'base','center','pos',[curvature_x_coordinate,curvature_y_coordinate],'rot','0');
g25 = geomcomp({g22,g24},'ns',{'CO2','C1'},'sf','CO2-C1','edge','none');
g26 = geomcomp({g14,g17,g25},'ns',{'g14','g17','g25'},'sf','g14+g17+g25','edge','none');
g27 = geomdel(g26);

% Analyzed geometry

clear s
s.objs = {g19,g27};
s.name = {'CO1','CO3'};
s.tags = {'g19','g27'};

fem.draw = struct('s',s);
fem.geom = geomcsg(fem);

% Constants

fem.const = {'rhoL','626.7', ...
	     'rhoV','3.10', ...
	     'muL','2.4e-4', ...
	     'muV','7.5e-6', ...
	     'rpm','5000', ...
	     'omega','rpm*2*pi/60', ...
	     'rsina','0.000539', ...
	     'dpBdz','17000', ...
	     'YL0','0.87', ...
	     'YV0','0.72', ...
	     'DL','5e-9', ...
	     'DV','3.4e-6', ...
	     'alpha','1.44' };

% (Default values are not included)
% Application mode 1

clear appl
appl.mode.class = 'FlPDEG';
appl.dim = { 'uL', ...
	     'vL', ...
	     'wL', ...
	     'pL', ...
	     'YL', ...
	     'uL_t', ...
	     'vL_t', ...
	     'wL_t', ...
	     'pL_t', ...
	     'YL_t' };
appl.name = 'liquid_phase';
appl.shape = {'shlag(2,''uL'')','shlag(2,''vL'')','shlag(2,''wL'')','shlag(2,''pL'')','shlag(2,''YL'')','shlag(1,''pL'')'};
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.assignsuffix = '_liquid_phase';
clear pnt
pnt.constr = {0,{0;0;0;'-pL'},{0;0;0;0;'-YL+YL0'}};
pnt.ind = [1,1,1,1,1,1,1,1,3,1,2];
appl.pnt = pnt;
clear bnd
bnd.type = 'dir';
bnd.r = {{'-uL';'-vL';'-wL';'-pL';'-YL'},{'-uL*nx-vL*ny';'-vL+vV';'-wL+wV'; ...
0;'-YL+YV*alpha/(1+(alpha-1)*YV)'},{'-uL';'-vL';'-wL'}};
bnd.ind = [1,3,1,1,3,3,1,2,3,2,2,2];
appl.bnd = bnd;
clear equ
equ.init = {0,{0;0;0;0;'YL0';0;0;0;0;0}};
equ.shape = {[1;2;3;4;5],[1;2;3;6;5]};
equ.cporder = {1,{1;1;1;2;1}};
equ.da = {1,{'rhoL';'rhoL';'rhoL';0;1}};
equ.gporder = {1,{1;1;1;2;1}};
equ.f = {1,{'-rhoL*uL*uLx-rhoL*vL*uLy';'-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL'; ...
	    '-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL';'uLx+vLy'; ...
	    '-wL*dYBdzL-uL*YLx-vL*YLy'}};
equ.usage = {0,1};
equ.ga = {{{'-uLx';'-uLy'};{'-vLx';'-vLy'};{'-wLx';'-wLy'};{'-pLx';'-pLy'}; ...
	   {'-YLx';'-YLy'}},{{'-muL*2*uLx+pL';'-muL*(uLy+vLx)'};{'-muL*(vLx+uLy)'; '-muL*2*vLy+pL'}; ...
			     {'-muL*wLx';'-muL*wLy'};{0;0};{'-DL*YLx';'-DL*YLy'}}};
equ.ind = [1,2];
appl.equ = equ;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'FlPDEG';
appl.dim = {'uV','vV','wV','pV','YV','uV_t','vV_t','wV_t','pV_t','YV_t'};
appl.name = 'vapour_phase';
appl.shape = {'shlag(2,''uV'')','shlag(2,''vV'')','shlag(2,''wV'')','shlag(1,''pV'')','shlag(2,''YV'')','shlag(2,''pV'')'};
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.assignsuffix = '_vapour_phase';
clear prop
clear weakconstr
weakconstr.value = 'off';
weakconstr.dim = {'lm11','lm12','lm13','lm14','lm15','lm16','lm17','lm18', ...
		  'lm19','lm20'};
prop.weakconstr = weakconstr;
appl.prop = prop;
clear pnt
pnt.constr = {0,{0;0;0;'-pV'}};
pnt.ind = [1,1,1,1,1,1,2,1,1,1,1];
appl.pnt = pnt;
clear bnd
bnd.type = 'dir';
bnd.r = {{'-uV';'-vV';'-wV';'-pV';'-YV'},{'-uV';'-vV';'-wV'},{'-uV*nx-vV*ny'; ...
							      '-vV+vL';'-wV+wL';0;'-YV+YL/(alpha-(alpha-1)*YL)'}};
bnd.ind = [2,1,2,2,1,1,2,3,1,3,3,3];
appl.bnd = bnd;
clear equ
equ.init = {{0;0;0;0;'YV0';0;0;0;0;0},0};
equ.shape = {[1;2;3;4;5],[1;2;3;6;5]};
equ.cporder = {{1;1;1;2;1},1};
equ.da = {{'rhoV';'rhoV';'rhoV';0;1},1};
equ.gporder = {{1;1;1;2;1},1};
equ.f = {{'-rhoV*uV*uVx-rhoV*vV*uVy';'-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV'; ...
	  '-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV';'uVx+vVy'; ...
	  '-wV*dYBdzV-uV*YVx-vV*YVy'},1};
equ.usage = {1,0};
equ.ga = {{{'-muV*2*uVx+pV';'-muV*(uVy+vVx)'};{'-muV*(vVx+uVy)';'-muV*2*vVy+pV'}; ...
	   {'-muV*wVx';'-muV*wVy'};{0;0};{'-DV*YVx';'-DV*YVy'}},{{'-uVx';'-uVy'}; ...
								 {'-vVx';'-vVy'};{'-wVx';'-wVy'};{'-pVx';'-pVy'};{'-YVx';'-YVy'}}};
equ.ind = [1,2];
appl.equ = equ;
fem.appl{2} = appl;

% Shape functions
fem.shape = {'shlag(2,''uV'')', ...
	     'shlag(2,''vV'')', ...
	     'shlag(2,''wV'')', ...
	     'shlag(1,''pV'')', ...
	     'shlag(2,''YV'')', ...
	     'shlag(2,''uL'')', ...
	     'shlag(2,''vL'')', ...
	     'shlag(2,''wL'')', ...
	     'shlag(1,''pL'')', ...
	     'shlag(2,''YL'')' };

% Integration order
fem.gporder = {4,2};

% Constraint order
fem.cporder = {2,1};
fem.border = 1;

% Equation form
fem.form = 'general';

% Geometry shape order
fem.sshape = 2;

% Simplify expressions
fem.simplify = 'on';
fem.border = 1;

% Subdomain settings
clear equ
equ.init = {{0;0;0;0;0;0;0;0;0;'YV0'},{0;0;0;0; ...
				       'YL0';0;0;0;0;0}};
equ.be = {{{0;0},{0;0},{0;0},{0;0},{0;0},{0;0}, ...
	   {0;0},{0;0},{0;0},{0;0};{0;0},{0;0},{0;0},{0; ...
	     0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0};{0;0}, ...
{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0; ...
0},{0;0};{0;0},{0;0},{0;0},{0;0},{0;0},{0;0}, ...
{0;0},{0;0},{0;0},{0;0};{0;0},{0;0},{0;0},{0; ...
0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0};{'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,uLx)'; ...
'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,uLy)'},{'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,vLx)'; ...
'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,vLy)'},{'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,wLx)'; ...
'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,wLy)'},{'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,pLx)'; ...
'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,pLy)'},{'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,YLx)'; ...
'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,YLy)'},{'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,uVx)'; ...
'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,uVy)'},{'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,vVx)'; ...
'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,vVy)'},{'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,wVx)'; ...
'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,wVy)'},{'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,pVx)'; ...
'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,pVy)'},{'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,YVx)'; ...
'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,YVy)'};{'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,uLx)'; ...
'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,uLy)'},{'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,vLx)'; ...
'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,vLy)'},{'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,wLx)'; ...
'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,wLy)'},{'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,pLx)'; ...
'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,pLy)'},{'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,YLx)'; ...
'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,YLy)'},{'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,uVx)'; ...
'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,uVy)'},{'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,vVx)'; ...
'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,vVy)'},{'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,wVx)'; ...
'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,wVy)'},{'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,pVx)'; ...
'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,pVy)'},{'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,YVx)'; ...
'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,YVy)'};{'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,uLx)'; ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,uLy)'}, ...
{'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,vLx)'; ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,vLy)'}, ...
{'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,wLx)'; ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,wLy)'}, ...
{'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,pLx)'; ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,pLy)'}, ...
{'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,YLx)'; ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,YLy)'}, ...
{'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,uVx)'; ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,uVy)'}, ...
{'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,vVx)'; ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,vVy)'}, ...
{'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,wVx)'; ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,wVy)'}, ...
{'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,pVx)'; ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,pVy)'}, ...
{'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,YVx)'; ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,YVy)'}; ...
{'-diff(uVx+vVy,uLx)';'-diff(uVx+vVy,uLy)'},{'-diff(uVx+vVy,vLx)';'-diff(uVx+vVy,vLy)'}, ...
{'-diff(uVx+vVy,wLx)';'-diff(uVx+vVy,wLy)'},{'-diff(uVx+vVy,pLx)';'-diff(uVx+vVy,pLy)'}, ...
{'-diff(uVx+vVy,YLx)';'-diff(uVx+vVy,YLy)'},{'-diff(uVx+vVy,uVx)';'-diff(uVx+vVy,uVy)'}, ...
{'-diff(uVx+vVy,vVx)';'-diff(uVx+vVy,vVy)'},{'-diff(uVx+vVy,wVx)';'-diff(uVx+vVy,wVy)'}, ...
{'-diff(uVx+vVy,pVx)';'-diff(uVx+vVy,pVy)'},{'-diff(uVx+vVy,YVx)';'-diff(uVx+vVy,YVy)'}; ...
{'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,uLx)';'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,uLy)'}, ...
{'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,vLx)';'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,vLy)'}, ...
{'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,wLx)';'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,wLy)'}, ...
{'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,pLx)';'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,pLy)'}, ...
{'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,YLx)';'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,YLy)'}, ...
{'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,uVx)';'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,uVy)'}, ...
{'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,vVx)';'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,vVy)'}, ...
{'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,wVx)';'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,wVy)'}, ...
{'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,pVx)';'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,pVy)'}, ...
{'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,YVx)';'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,YVy)'}}, ...
{{'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,uLx)';'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,uLy)'}, ...
{'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,vLx)';'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,vLy)'}, ...
{'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,wLx)';'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,wLy)'}, ...
{'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,pLx)';'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,pLy)'}, ...
{'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,YLx)';'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,YLy)'}, ...
{'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,uVx)';'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,uVy)'}, ...
{'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,vVx)';'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,vVy)'}, ...
{'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,wVx)';'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,wVy)'}, ...
{'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,pVx)';'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,pVy)'}, ...
{'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,YVx)';'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,YVy)'}; ...
{'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,uLx)';'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,uLy)'}, ...
{'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,vLx)';'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,vLy)'}, ...
{'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,wLx)';'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,wLy)'}, ...
{'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,pLx)';'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,pLy)'}, ...
{'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,YLx)';'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,YLy)'}, ...
{'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,uVx)';'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,uVy)'}, ...
{'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,vVx)';'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,vVy)'}, ...
{'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,wVx)';'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,wVy)'}, ...
{'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,pVx)';'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,pVy)'}, ...
{'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,YVx)';'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,YVy)'}; ...
{'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,uLx)'; ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,uLy)'}, ...
{'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,vLx)'; ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,vLy)'}, ...
{'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,wLx)'; ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,wLy)'}, ...
{'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,pLx)'; ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,pLy)'}, ...
{'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,YLx)'; ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,YLy)'}, ...
{'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,uVx)'; ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,uVy)'}, ...
{'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,vVx)'; ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,vVy)'}, ...
{'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,wVx)'; ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,wVy)'}, ...
{'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,pVx)'; ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,pVy)'}, ...
{'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,YVx)'; ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,YVy)'}; ...
{'-diff(uLx+vLy,uLx)';'-diff(uLx+vLy,uLy)'},{'-diff(uLx+vLy,vLx)';'-diff(uLx+vLy,vLy)'}, ...
{'-diff(uLx+vLy,wLx)';'-diff(uLx+vLy,wLy)'},{'-diff(uLx+vLy,pLx)';'-diff(uLx+vLy,pLy)'}, ...
{'-diff(uLx+vLy,YLx)';'-diff(uLx+vLy,YLy)'},{'-diff(uLx+vLy,uVx)';'-diff(uLx+vLy,uVy)'}, ...
{'-diff(uLx+vLy,vVx)';'-diff(uLx+vLy,vVy)'},{'-diff(uLx+vLy,wVx)';'-diff(uLx+vLy,wVy)'}, ...
{'-diff(uLx+vLy,pVx)';'-diff(uLx+vLy,pVy)'},{'-diff(uLx+vLy,YVx)';'-diff(uLx+vLy,YVy)'}; ...
{'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,uLx)';'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,uLy)'}, ...
{'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,vLx)';'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,vLy)'}, ...
{'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,wLx)';'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,wLy)'}, ...
{'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,pLx)';'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,pLy)'}, ...
{'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,YLx)';'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,YLy)'}, ...
{'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,uVx)';'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,uVy)'}, ...
{'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,vVx)';'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,vVy)'}, ...
{'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,wVx)';'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,wVy)'}, ...
{'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,pVx)';'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,pVy)'}, ...
{'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,YVx)';'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,YVy)'}; ...
{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0; ...
0},{0;0},{0;0};{0;0},{0;0},{0;0},{0;0},{0;0}, ...
{0;0},{0;0},{0;0},{0;0},{0;0};{0;0},{0;0},{0; ...
0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0}; ...
{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0; ...
0},{0;0},{0;0};{0;0},{0;0},{0;0},{0;0},{0;0}, ...
{0;0},{0;0},{0;0},{0;0},{0;0}}};
equ.shape = {[1;2;3;4;5],[6;7;8;9;10]};
equ.c = {{0,0,0,0,0,0,0,0,0,0;0,0,0,0,0, ...
0,0,0,0,0;0,0,0,0,0,0,0,0,0,0;0,0,0, ...
0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0;{'-diff(-2*muV*uVx+pV,uLx)', ...
'-diff(-2*muV*uVx+pV,uLy)';'-diff(-muV*(uVy+vVx),uLx)','-diff(-muV*(uVy+vVx),uLy)'}, ...
{'-diff(-2*muV*uVx+pV,vLx)','-diff(-2*muV*uVx+pV,vLy)';'-diff(-muV*(uVy+vVx),vLx)', ...
'-diff(-muV*(uVy+vVx),vLy)'},{'-diff(-2*muV*uVx+pV,wLx)','-diff(-2*muV*uVx+pV,wLy)'; ...
'-diff(-muV*(uVy+vVx),wLx)','-diff(-muV*(uVy+vVx),wLy)'},{'-diff(-2*muV*uVx+pV,pLx)', ...
'-diff(-2*muV*uVx+pV,pLy)';'-diff(-muV*(uVy+vVx),pLx)','-diff(-muV*(uVy+vVx),pLy)'}, ...
{'-diff(-2*muV*uVx+pV,YLx)','-diff(-2*muV*uVx+pV,YLy)';'-diff(-muV*(uVy+vVx),YLx)', ...
'-diff(-muV*(uVy+vVx),YLy)'},{'-diff(-2*muV*uVx+pV,uVx)','-diff(-2*muV*uVx+pV,uVy)'; ...
'-diff(-muV*(uVy+vVx),uVx)','-diff(-muV*(uVy+vVx),uVy)'},{'-diff(-2*muV*uVx+pV,vVx)', ...
'-diff(-2*muV*uVx+pV,vVy)';'-diff(-muV*(uVy+vVx),vVx)','-diff(-muV*(uVy+vVx),vVy)'}, ...
{'-diff(-2*muV*uVx+pV,wVx)','-diff(-2*muV*uVx+pV,wVy)';'-diff(-muV*(uVy+vVx),wVx)', ...
'-diff(-muV*(uVy+vVx),wVy)'},{'-diff(-2*muV*uVx+pV,pVx)','-diff(-2*muV*uVx+pV,pVy)'; ...
'-diff(-muV*(uVy+vVx),pVx)','-diff(-muV*(uVy+vVx),pVy)'},{'-diff(-2*muV*uVx+pV,YVx)', ...
'-diff(-2*muV*uVx+pV,YVy)';'-diff(-muV*(uVy+vVx),YVx)','-diff(-muV*(uVy+vVx),YVy)'}; ...
{'-diff(-muV*(vVx+uVy),uLx)','-diff(-muV*(vVx+uVy),uLy)';'-diff(-2*muV*vVy+pV,uLx)', ...
'-diff(-2*muV*vVy+pV,uLy)'},{'-diff(-muV*(vVx+uVy),vLx)','-diff(-muV*(vVx+uVy),vLy)'; ...
'-diff(-2*muV*vVy+pV,vLx)','-diff(-2*muV*vVy+pV,vLy)'},{'-diff(-muV*(vVx+uVy),wLx)', ...
'-diff(-muV*(vVx+uVy),wLy)';'-diff(-2*muV*vVy+pV,wLx)','-diff(-2*muV*vVy+pV,wLy)'}, ...
{'-diff(-muV*(vVx+uVy),pLx)','-diff(-muV*(vVx+uVy),pLy)';'-diff(-2*muV*vVy+pV,pLx)', ...
'-diff(-2*muV*vVy+pV,pLy)'},{'-diff(-muV*(vVx+uVy),YLx)','-diff(-muV*(vVx+uVy),YLy)'; ...
'-diff(-2*muV*vVy+pV,YLx)','-diff(-2*muV*vVy+pV,YLy)'},{'-diff(-muV*(vVx+uVy),uVx)', ...
'-diff(-muV*(vVx+uVy),uVy)';'-diff(-2*muV*vVy+pV,uVx)','-diff(-2*muV*vVy+pV,uVy)'}, ...
{'-diff(-muV*(vVx+uVy),vVx)','-diff(-muV*(vVx+uVy),vVy)';'-diff(-2*muV*vVy+pV,vVx)', ...
'-diff(-2*muV*vVy+pV,vVy)'},{'-diff(-muV*(vVx+uVy),wVx)','-diff(-muV*(vVx+uVy),wVy)'; ...
'-diff(-2*muV*vVy+pV,wVx)','-diff(-2*muV*vVy+pV,wVy)'},{'-diff(-muV*(vVx+uVy),pVx)', ...
'-diff(-muV*(vVx+uVy),pVy)';'-diff(-2*muV*vVy+pV,pVx)','-diff(-2*muV*vVy+pV,pVy)'}, ...
{'-diff(-muV*(vVx+uVy),YVx)','-diff(-muV*(vVx+uVy),YVy)';'-diff(-2*muV*vVy+pV,YVx)', ...
'-diff(-2*muV*vVy+pV,YVy)'};{'-diff(-muV*wVx,uLx)','-diff(-muV*wVx,uLy)'; ...
'-diff(-muV*wVy,uLx)','-diff(-muV*wVy,uLy)'},{'-diff(-muV*wVx,vLx)','-diff(-muV*wVx,vLy)'; ...
'-diff(-muV*wVy,vLx)','-diff(-muV*wVy,vLy)'},{'-diff(-muV*wVx,wLx)','-diff(-muV*wVx,wLy)'; ...
'-diff(-muV*wVy,wLx)','-diff(-muV*wVy,wLy)'},{'-diff(-muV*wVx,pLx)','-diff(-muV*wVx,pLy)'; ...
'-diff(-muV*wVy,pLx)','-diff(-muV*wVy,pLy)'},{'-diff(-muV*wVx,YLx)','-diff(-muV*wVx,YLy)'; ...
'-diff(-muV*wVy,YLx)','-diff(-muV*wVy,YLy)'},{'-diff(-muV*wVx,uVx)','-diff(-muV*wVx,uVy)'; ...
'-diff(-muV*wVy,uVx)','-diff(-muV*wVy,uVy)'},{'-diff(-muV*wVx,vVx)','-diff(-muV*wVx,vVy)'; ...
'-diff(-muV*wVy,vVx)','-diff(-muV*wVy,vVy)'},{'-diff(-muV*wVx,wVx)','-diff(-muV*wVx,wVy)'; ...
'-diff(-muV*wVy,wVx)','-diff(-muV*wVy,wVy)'},{'-diff(-muV*wVx,pVx)','-diff(-muV*wVx,pVy)'; ...
'-diff(-muV*wVy,pVx)','-diff(-muV*wVy,pVy)'},{'-diff(-muV*wVx,YVx)','-diff(-muV*wVx,YVy)'; ...
'-diff(-muV*wVy,YVx)','-diff(-muV*wVy,YVy)'};0,0,0,0,0,0,0, ...
0,0,0;{'-diff(-DV*YVx,uLx)','-diff(-DV*YVx,uLy)';'-diff(-DV*YVy,uLx)', ...
'-diff(-DV*YVy,uLy)'},{'-diff(-DV*YVx,vLx)','-diff(-DV*YVx,vLy)';'-diff(-DV*YVy,vLx)', ...
'-diff(-DV*YVy,vLy)'},{'-diff(-DV*YVx,wLx)','-diff(-DV*YVx,wLy)';'-diff(-DV*YVy,wLx)', ...
'-diff(-DV*YVy,wLy)'},{'-diff(-DV*YVx,pLx)','-diff(-DV*YVx,pLy)';'-diff(-DV*YVy,pLx)', ...
'-diff(-DV*YVy,pLy)'},{'-diff(-DV*YVx,YLx)','-diff(-DV*YVx,YLy)';'-diff(-DV*YVy,YLx)', ...
'-diff(-DV*YVy,YLy)'},{'-diff(-DV*YVx,uVx)','-diff(-DV*YVx,uVy)';'-diff(-DV*YVy,uVx)', ...
'-diff(-DV*YVy,uVy)'},{'-diff(-DV*YVx,vVx)','-diff(-DV*YVx,vVy)';'-diff(-DV*YVy,vVx)', ...
'-diff(-DV*YVy,vVy)'},{'-diff(-DV*YVx,wVx)','-diff(-DV*YVx,wVy)';'-diff(-DV*YVy,wVx)', ...
'-diff(-DV*YVy,wVy)'},{'-diff(-DV*YVx,pVx)','-diff(-DV*YVx,pVy)';'-diff(-DV*YVy,pVx)', ...
'-diff(-DV*YVy,pVy)'},{'-diff(-DV*YVx,YVx)','-diff(-DV*YVx,YVy)';'-diff(-DV*YVy,YVx)', ...
'-diff(-DV*YVy,YVy)'}},{{'-diff(-2*muL*uLx+pL,uLx)','-diff(-2*muL*uLx+pL,uLy)'; ...
'-diff(-muL*(uLy+vLx),uLx)','-diff(-muL*(uLy+vLx),uLy)'},{'-diff(-2*muL*uLx+pL,vLx)', ...
'-diff(-2*muL*uLx+pL,vLy)';'-diff(-muL*(uLy+vLx),vLx)','-diff(-muL*(uLy+vLx),vLy)'}, ...
{'-diff(-2*muL*uLx+pL,wLx)','-diff(-2*muL*uLx+pL,wLy)';'-diff(-muL*(uLy+vLx),wLx)', ...
'-diff(-muL*(uLy+vLx),wLy)'},{'-diff(-2*muL*uLx+pL,pLx)','-diff(-2*muL*uLx+pL,pLy)'; ...
'-diff(-muL*(uLy+vLx),pLx)','-diff(-muL*(uLy+vLx),pLy)'},{'-diff(-2*muL*uLx+pL,YLx)', ...
'-diff(-2*muL*uLx+pL,YLy)';'-diff(-muL*(uLy+vLx),YLx)','-diff(-muL*(uLy+vLx),YLy)'}, ...
{'-diff(-2*muL*uLx+pL,uVx)','-diff(-2*muL*uLx+pL,uVy)';'-diff(-muL*(uLy+vLx),uVx)', ...
'-diff(-muL*(uLy+vLx),uVy)'},{'-diff(-2*muL*uLx+pL,vVx)','-diff(-2*muL*uLx+pL,vVy)'; ...
'-diff(-muL*(uLy+vLx),vVx)','-diff(-muL*(uLy+vLx),vVy)'},{'-diff(-2*muL*uLx+pL,wVx)', ...
'-diff(-2*muL*uLx+pL,wVy)';'-diff(-muL*(uLy+vLx),wVx)','-diff(-muL*(uLy+vLx),wVy)'}, ...
{'-diff(-2*muL*uLx+pL,pVx)','-diff(-2*muL*uLx+pL,pVy)';'-diff(-muL*(uLy+vLx),pVx)', ...
'-diff(-muL*(uLy+vLx),pVy)'},{'-diff(-2*muL*uLx+pL,YVx)','-diff(-2*muL*uLx+pL,YVy)'; ...
'-diff(-muL*(uLy+vLx),YVx)','-diff(-muL*(uLy+vLx),YVy)'};{'-diff(-muL*(vLx+uLy),uLx)', ...
'-diff(-muL*(vLx+uLy),uLy)';'-diff(-2*muL*vLy+pL,uLx)','-diff(-2*muL*vLy+pL,uLy)'}, ...
{'-diff(-muL*(vLx+uLy),vLx)','-diff(-muL*(vLx+uLy),vLy)';'-diff(-2*muL*vLy+pL,vLx)', ...
'-diff(-2*muL*vLy+pL,vLy)'},{'-diff(-muL*(vLx+uLy),wLx)','-diff(-muL*(vLx+uLy),wLy)'; ...
'-diff(-2*muL*vLy+pL,wLx)','-diff(-2*muL*vLy+pL,wLy)'},{'-diff(-muL*(vLx+uLy),pLx)', ...
'-diff(-muL*(vLx+uLy),pLy)';'-diff(-2*muL*vLy+pL,pLx)','-diff(-2*muL*vLy+pL,pLy)'}, ...
{'-diff(-muL*(vLx+uLy),YLx)','-diff(-muL*(vLx+uLy),YLy)';'-diff(-2*muL*vLy+pL,YLx)', ...
'-diff(-2*muL*vLy+pL,YLy)'},{'-diff(-muL*(vLx+uLy),uVx)','-diff(-muL*(vLx+uLy),uVy)'; ...
'-diff(-2*muL*vLy+pL,uVx)','-diff(-2*muL*vLy+pL,uVy)'},{'-diff(-muL*(vLx+uLy),vVx)', ...
'-diff(-muL*(vLx+uLy),vVy)';'-diff(-2*muL*vLy+pL,vVx)','-diff(-2*muL*vLy+pL,vVy)'}, ...
{'-diff(-muL*(vLx+uLy),wVx)','-diff(-muL*(vLx+uLy),wVy)';'-diff(-2*muL*vLy+pL,wVx)', ...
'-diff(-2*muL*vLy+pL,wVy)'},{'-diff(-muL*(vLx+uLy),pVx)','-diff(-muL*(vLx+uLy),pVy)'; ...
'-diff(-2*muL*vLy+pL,pVx)','-diff(-2*muL*vLy+pL,pVy)'},{'-diff(-muL*(vLx+uLy),YVx)', ...
'-diff(-muL*(vLx+uLy),YVy)';'-diff(-2*muL*vLy+pL,YVx)','-diff(-2*muL*vLy+pL,YVy)'}; ...
{'-diff(-muL*wLx,uLx)','-diff(-muL*wLx,uLy)';'-diff(-muL*wLy,uLx)','-diff(-muL*wLy,uLy)'}, ...
{'-diff(-muL*wLx,vLx)','-diff(-muL*wLx,vLy)';'-diff(-muL*wLy,vLx)','-diff(-muL*wLy,vLy)'}, ...
{'-diff(-muL*wLx,wLx)','-diff(-muL*wLx,wLy)';'-diff(-muL*wLy,wLx)','-diff(-muL*wLy,wLy)'}, ...
{'-diff(-muL*wLx,pLx)','-diff(-muL*wLx,pLy)';'-diff(-muL*wLy,pLx)','-diff(-muL*wLy,pLy)'}, ...
{'-diff(-muL*wLx,YLx)','-diff(-muL*wLx,YLy)';'-diff(-muL*wLy,YLx)','-diff(-muL*wLy,YLy)'}, ...
{'-diff(-muL*wLx,uVx)','-diff(-muL*wLx,uVy)';'-diff(-muL*wLy,uVx)','-diff(-muL*wLy,uVy)'}, ...
{'-diff(-muL*wLx,vVx)','-diff(-muL*wLx,vVy)';'-diff(-muL*wLy,vVx)','-diff(-muL*wLy,vVy)'}, ...
{'-diff(-muL*wLx,wVx)','-diff(-muL*wLx,wVy)';'-diff(-muL*wLy,wVx)','-diff(-muL*wLy,wVy)'}, ...
{'-diff(-muL*wLx,pVx)','-diff(-muL*wLx,pVy)';'-diff(-muL*wLy,pVx)','-diff(-muL*wLy,pVy)'}, ...
{'-diff(-muL*wLx,YVx)','-diff(-muL*wLx,YVy)';'-diff(-muL*wLy,YVx)','-diff(-muL*wLy,YVy)'}; ...
0,0,0,0,0,0,0,0,0,0;{'-diff(-DL*YLx,uLx)','-diff(-DL*YLx,uLy)'; ...
'-diff(-DL*YLy,uLx)','-diff(-DL*YLy,uLy)'},{'-diff(-DL*YLx,vLx)','-diff(-DL*YLx,vLy)'; ...
'-diff(-DL*YLy,vLx)','-diff(-DL*YLy,vLy)'},{'-diff(-DL*YLx,wLx)','-diff(-DL*YLx,wLy)'; ...
'-diff(-DL*YLy,wLx)','-diff(-DL*YLy,wLy)'},{'-diff(-DL*YLx,pLx)','-diff(-DL*YLx,pLy)'; ...
'-diff(-DL*YLy,pLx)','-diff(-DL*YLy,pLy)'},{'-diff(-DL*YLx,YLx)','-diff(-DL*YLx,YLy)'; ...
'-diff(-DL*YLy,YLx)','-diff(-DL*YLy,YLy)'},{'-diff(-DL*YLx,uVx)','-diff(-DL*YLx,uVy)'; ...
'-diff(-DL*YLy,uVx)','-diff(-DL*YLy,uVy)'},{'-diff(-DL*YLx,vVx)','-diff(-DL*YLx,vVy)'; ...
'-diff(-DL*YLy,vVx)','-diff(-DL*YLy,vVy)'},{'-diff(-DL*YLx,wVx)','-diff(-DL*YLx,wVy)'; ...
'-diff(-DL*YLy,wVx)','-diff(-DL*YLy,wVy)'},{'-diff(-DL*YLx,pVx)','-diff(-DL*YLx,pVy)'; ...
'-diff(-DL*YLy,pVx)','-diff(-DL*YLy,pVy)'},{'-diff(-DL*YLx,YVx)','-diff(-DL*YLx,YVy)'; ...
'-diff(-DL*YLy,YVx)','-diff(-DL*YLy,YVy)'};0,0,0,0,0,0,0, ...
0,0,0;0,0,0,0,0,0,0,0,0,0;0,0,0,0,0, ...
0,0,0,0,0;0,0,0,0,0,0,0,0,0,0;0,0,0, ...
0,0,0,0,0,0,0}};
equ.cporder = {{1;1;1;1;1;1;1;1;2;1},{1;1;1;2;1;1;1;1;1;1}};
equ.da = {{0;0;0;0;0;'rhoV';'rhoV';'rhoV';0;1},{'rhoL';'rhoL'; ...
'rhoL';0;1;0;0;0;0;0}};
equ.gporder = {{1;1;1;1;1;1;1;1;2;1},{1;1;1;2;1;1;1;1;1;1}};
equ.al = {{{0;0},{0;0},{0;0},{0;0},{0;0},{0;0}, ...
{0;0},{0;0},{0;0},{0;0};{0;0},{0;0},{0;0},{0; ...
0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0};{0;0}, ...
{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0; ...
0},{0;0};{0;0},{0;0},{0;0},{0;0},{0;0},{0;0}, ...
{0;0},{0;0},{0;0},{0;0};{0;0},{0;0},{0;0},{0; ...
0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0};{'-diff(-2*muV*uVx+pV,uL)'; ...
'-diff(-muV*(uVy+vVx),uL)'},{'-diff(-2*muV*uVx+pV,vL)';'-diff(-muV*(uVy+vVx),vL)'}, ...
{'-diff(-2*muV*uVx+pV,wL)';'-diff(-muV*(uVy+vVx),wL)'},{'-diff(-2*muV*uVx+pV,pL)'; ...
'-diff(-muV*(uVy+vVx),pL)'},{'-diff(-2*muV*uVx+pV,YL)';'-diff(-muV*(uVy+vVx),YL)'}, ...
{'-diff(-2*muV*uVx+pV,uV)';'-diff(-muV*(uVy+vVx),uV)'},{'-diff(-2*muV*uVx+pV,vV)'; ...
'-diff(-muV*(uVy+vVx),vV)'},{'-diff(-2*muV*uVx+pV,wV)';'-diff(-muV*(uVy+vVx),wV)'}, ...
{'-diff(-2*muV*uVx+pV,pV)';'-diff(-muV*(uVy+vVx),pV)'},{'-diff(-2*muV*uVx+pV,YV)'; ...
'-diff(-muV*(uVy+vVx),YV)'};{'-diff(-muV*(vVx+uVy),uL)';'-diff(-2*muV*vVy+pV,uL)'}, ...
{'-diff(-muV*(vVx+uVy),vL)';'-diff(-2*muV*vVy+pV,vL)'},{'-diff(-muV*(vVx+uVy),wL)'; ...
'-diff(-2*muV*vVy+pV,wL)'},{'-diff(-muV*(vVx+uVy),pL)';'-diff(-2*muV*vVy+pV,pL)'}, ...
{'-diff(-muV*(vVx+uVy),YL)';'-diff(-2*muV*vVy+pV,YL)'},{'-diff(-muV*(vVx+uVy),uV)'; ...
'-diff(-2*muV*vVy+pV,uV)'},{'-diff(-muV*(vVx+uVy),vV)';'-diff(-2*muV*vVy+pV,vV)'}, ...
{'-diff(-muV*(vVx+uVy),wV)';'-diff(-2*muV*vVy+pV,wV)'},{'-diff(-muV*(vVx+uVy),pV)'; ...
'-diff(-2*muV*vVy+pV,pV)'},{'-diff(-muV*(vVx+uVy),YV)';'-diff(-2*muV*vVy+pV,YV)'}; ...
{'-diff(-muV*wVx,uL)';'-diff(-muV*wVy,uL)'},{'-diff(-muV*wVx,vL)';'-diff(-muV*wVy,vL)'}, ...
{'-diff(-muV*wVx,wL)';'-diff(-muV*wVy,wL)'},{'-diff(-muV*wVx,pL)';'-diff(-muV*wVy,pL)'}, ...
{'-diff(-muV*wVx,YL)';'-diff(-muV*wVy,YL)'},{'-diff(-muV*wVx,uV)';'-diff(-muV*wVy,uV)'}, ...
{'-diff(-muV*wVx,vV)';'-diff(-muV*wVy,vV)'},{'-diff(-muV*wVx,wV)';'-diff(-muV*wVy,wV)'}, ...
{'-diff(-muV*wVx,pV)';'-diff(-muV*wVy,pV)'},{'-diff(-muV*wVx,YV)';'-diff(-muV*wVy,YV)'}; ...
{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0; ...
0},{0;0},{0;0};{'-diff(-DV*YVx,uL)';'-diff(-DV*YVy,uL)'},{'-diff(-DV*YVx,vL)'; ...
'-diff(-DV*YVy,vL)'},{'-diff(-DV*YVx,wL)';'-diff(-DV*YVy,wL)'},{'-diff(-DV*YVx,pL)'; ...
'-diff(-DV*YVy,pL)'},{'-diff(-DV*YVx,YL)';'-diff(-DV*YVy,YL)'},{'-diff(-DV*YVx,uV)'; ...
'-diff(-DV*YVy,uV)'},{'-diff(-DV*YVx,vV)';'-diff(-DV*YVy,vV)'},{'-diff(-DV*YVx,wV)'; ...
'-diff(-DV*YVy,wV)'},{'-diff(-DV*YVx,pV)';'-diff(-DV*YVy,pV)'},{'-diff(-DV*YVx,YV)'; ...
'-diff(-DV*YVy,YV)'}},{{'-diff(-2*muL*uLx+pL,uL)';'-diff(-muL*(uLy+vLx),uL)'}, ...
{'-diff(-2*muL*uLx+pL,vL)';'-diff(-muL*(uLy+vLx),vL)'},{'-diff(-2*muL*uLx+pL,wL)'; ...
'-diff(-muL*(uLy+vLx),wL)'},{'-diff(-2*muL*uLx+pL,pL)';'-diff(-muL*(uLy+vLx),pL)'}, ...
{'-diff(-2*muL*uLx+pL,YL)';'-diff(-muL*(uLy+vLx),YL)'},{'-diff(-2*muL*uLx+pL,uV)'; ...
'-diff(-muL*(uLy+vLx),uV)'},{'-diff(-2*muL*uLx+pL,vV)';'-diff(-muL*(uLy+vLx),vV)'}, ...
{'-diff(-2*muL*uLx+pL,wV)';'-diff(-muL*(uLy+vLx),wV)'},{'-diff(-2*muL*uLx+pL,pV)'; ...
'-diff(-muL*(uLy+vLx),pV)'},{'-diff(-2*muL*uLx+pL,YV)';'-diff(-muL*(uLy+vLx),YV)'}; ...
{'-diff(-muL*(vLx+uLy),uL)';'-diff(-2*muL*vLy+pL,uL)'},{'-diff(-muL*(vLx+uLy),vL)'; ...
'-diff(-2*muL*vLy+pL,vL)'},{'-diff(-muL*(vLx+uLy),wL)';'-diff(-2*muL*vLy+pL,wL)'}, ...
{'-diff(-muL*(vLx+uLy),pL)';'-diff(-2*muL*vLy+pL,pL)'},{'-diff(-muL*(vLx+uLy),YL)'; ...
'-diff(-2*muL*vLy+pL,YL)'},{'-diff(-muL*(vLx+uLy),uV)';'-diff(-2*muL*vLy+pL,uV)'}, ...
{'-diff(-muL*(vLx+uLy),vV)';'-diff(-2*muL*vLy+pL,vV)'},{'-diff(-muL*(vLx+uLy),wV)'; ...
'-diff(-2*muL*vLy+pL,wV)'},{'-diff(-muL*(vLx+uLy),pV)';'-diff(-2*muL*vLy+pL,pV)'}, ...
{'-diff(-muL*(vLx+uLy),YV)';'-diff(-2*muL*vLy+pL,YV)'};{'-diff(-muL*wLx,uL)'; ...
'-diff(-muL*wLy,uL)'},{'-diff(-muL*wLx,vL)';'-diff(-muL*wLy,vL)'},{'-diff(-muL*wLx,wL)'; ...
'-diff(-muL*wLy,wL)'},{'-diff(-muL*wLx,pL)';'-diff(-muL*wLy,pL)'},{'-diff(-muL*wLx,YL)'; ...
'-diff(-muL*wLy,YL)'},{'-diff(-muL*wLx,uV)';'-diff(-muL*wLy,uV)'},{'-diff(-muL*wLx,vV)'; ...
'-diff(-muL*wLy,vV)'},{'-diff(-muL*wLx,wV)';'-diff(-muL*wLy,wV)'},{'-diff(-muL*wLx,pV)'; ...
'-diff(-muL*wLy,pV)'},{'-diff(-muL*wLx,YV)';'-diff(-muL*wLy,YV)'};{0; ...
0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0}, ...
{0;0},{0;0};{'-diff(-DL*YLx,uL)';'-diff(-DL*YLy,uL)'},{'-diff(-DL*YLx,vL)'; ...
'-diff(-DL*YLy,vL)'},{'-diff(-DL*YLx,wL)';'-diff(-DL*YLy,wL)'},{'-diff(-DL*YLx,pL)'; ...
'-diff(-DL*YLy,pL)'},{'-diff(-DL*YLx,YL)';'-diff(-DL*YLy,YL)'},{'-diff(-DL*YLx,uV)'; ...
'-diff(-DL*YLy,uV)'},{'-diff(-DL*YLx,vV)';'-diff(-DL*YLy,vV)'},{'-diff(-DL*YLx,wV)'; ...
'-diff(-DL*YLy,wV)'},{'-diff(-DL*YLx,pV)';'-diff(-DL*YLy,pV)'},{'-diff(-DL*YLx,YV)'; ...
'-diff(-DL*YLy,YV)'};{0;0},{0;0},{0;0},{0;0},{0;0}, ...
{0;0},{0;0},{0;0},{0;0},{0;0};{0;0},{0;0},{0; ...
0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0}; ...
{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0; ...
0},{0;0},{0;0};{0;0},{0;0},{0;0},{0;0},{0;0}, ...
{0;0},{0;0},{0;0},{0;0},{0;0};{0;0},{0;0},{0; ...
0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0},{0;0}}};
equ.a = {{0,0,0,0,0,0,0,0,0,0;0,0,0,0,0, ...
0,0,0,0,0;0,0,0,0,0,0,0,0,0,0;0,0,0, ...
0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0;'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,uL)', ...
'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,vL)','-diff(-rhoV*uV*uVx-rhoV*vV*uVy,wL)', ...
'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,pL)','-diff(-rhoV*uV*uVx-rhoV*vV*uVy,YL)', ...
'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,uV)','-diff(-rhoV*uV*uVx-rhoV*vV*uVy,vV)', ...
'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,wV)','-diff(-rhoV*uV*uVx-rhoV*vV*uVy,pV)', ...
'-diff(-rhoV*uV*uVx-rhoV*vV*uVy,YV)';'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,uL)', ...
'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,vL)','-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,wL)', ...
'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,pL)','-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,YL)', ...
'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,uV)','-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,vV)', ...
'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,wV)','-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,pV)', ...
'-diff(-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV,YV)';'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,uL)', ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,vL)', ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,wL)', ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,pL)', ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,YL)', ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,uV)', ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,vV)', ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,wV)', ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,pV)', ...
'-diff(-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV,YV)'; ...
'-diff(uVx+vVy,uL)','-diff(uVx+vVy,vL)','-diff(uVx+vVy,wL)','-diff(uVx+vVy,pL)', ...
'-diff(uVx+vVy,YL)','-diff(uVx+vVy,uV)','-diff(uVx+vVy,vV)','-diff(uVx+vVy,wV)', ...
'-diff(uVx+vVy,pV)','-diff(uVx+vVy,YV)';'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,uL)', ...
'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,vL)','-diff(-wV*dYBdzV-uV*YVx-vV*YVy,wL)', ...
'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,pL)','-diff(-wV*dYBdzV-uV*YVx-vV*YVy,YL)', ...
'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,uV)','-diff(-wV*dYBdzV-uV*YVx-vV*YVy,vV)', ...
'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,wV)','-diff(-wV*dYBdzV-uV*YVx-vV*YVy,pV)', ...
'-diff(-wV*dYBdzV-uV*YVx-vV*YVy,YV)'},{'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,uL)', ...
'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,vL)','-diff(-rhoL*uL*uLx-rhoL*vL*uLy,wL)', ...
'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,pL)','-diff(-rhoL*uL*uLx-rhoL*vL*uLy,YL)', ...
'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,uV)','-diff(-rhoL*uL*uLx-rhoL*vL*uLy,vV)', ...
'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,wV)','-diff(-rhoL*uL*uLx-rhoL*vL*uLy,pV)', ...
'-diff(-rhoL*uL*uLx-rhoL*vL*uLy,YV)';'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,uL)', ...
'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,vL)','-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,wL)', ...
'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,pL)','-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,YL)', ...
'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,uV)','-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,vV)', ...
'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,wV)','-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,pV)', ...
'-diff(-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL,YV)';'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,uL)', ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,vL)', ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,wL)', ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,pL)', ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,YL)', ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,uV)', ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,vV)', ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,wV)', ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,pV)', ...
'-diff(-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL,YV)'; ...
'-diff(uLx+vLy,uL)','-diff(uLx+vLy,vL)','-diff(uLx+vLy,wL)','-diff(uLx+vLy,pL)', ...
'-diff(uLx+vLy,YL)','-diff(uLx+vLy,uV)','-diff(uLx+vLy,vV)','-diff(uLx+vLy,wV)', ...
'-diff(uLx+vLy,pV)','-diff(uLx+vLy,YV)';'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,uL)', ...
'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,vL)','-diff(-wL*dYBdzL-uL*YLx-vL*YLy,wL)', ...
'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,pL)','-diff(-wL*dYBdzL-uL*YLx-vL*YLy,YL)', ...
'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,uV)','-diff(-wL*dYBdzL-uL*YLx-vL*YLy,vV)', ...
'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,wV)','-diff(-wL*dYBdzL-uL*YLx-vL*YLy,pV)', ...
'-diff(-wL*dYBdzL-uL*YLx-vL*YLy,YV)';0,0,0,0,0,0,0,0,0, ...
0;0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0, ...
0,0,0;0,0,0,0,0,0,0,0,0,0;0,0,0,0,0, ...
0,0,0,0,0}};
equ.f = {{0;0;0;0;0;'-rhoV*uV*uVx-rhoV*vV*uVy';'-rhoV*uV*vVx-rhoV*vV*vVy+2*rhoV*omega*wV'; ...
'-dpBdz-rhoV*uV*wVx-rhoV*vV*wVy+rhoV*omega^2*rsina-2*rhoV*omega*vV';'uVx+vVy'; ...
'-wV*dYBdzV-uV*YVx-vV*YVy'},{'-rhoL*uL*uLx-rhoL*vL*uLy';'-rhoL*uL*vLx-rhoL*vL*vLy+2*rhoL*omega*wL'; ...
'-dpBdz-rhoL*uL*wLx-rhoL*vL*wLy+rhoL*omega^2*rsina-2*rhoL*omega*vL';'uLx+vLy'; ...
'-wL*dYBdzL-uL*YLx-vL*YLy';0;0;0;0;0}};
equ.ga = {{{0;0};{0;0};{0;0};{0;0};{0;0};{'-2*muV*uVx+pV'; ...
'-muV*(uVy+vVx)'};{'-muV*(vVx+uVy)';'-2*muV*vVy+pV'};{'-muV*wVx';'-muV*wVy'}; ...
{0;0};{'-DV*YVx';'-DV*YVy'}},{{'-2*muL*uLx+pL';'-muL*(uLy+vLx)'};{'-muL*(vLx+uLy)'; ...
'-2*muL*vLy+pL'};{'-muL*wLx';'-muL*wLy'};{0;0};{'-DL*YLx';'-DL*YLy'}; ...
{0;0};{0;0};{0;0};{0;0};{0;0}}};
equ.ind = [1,2];
equ.dim = {'uL','vL','wL','pL','YL','uV','vV','wV','pV','YV'};
equ.var = {'absuLx_liquid_phase',{'','sqrt(uLx^2+uLy^2)'}, ...
'absga1x_liquid_phase',{'','sqrt(ga1x^2+ga1y^2)'}, ...
'absvLx_liquid_phase',{'','sqrt(vLx^2+vLy^2)'}, ...
'absga2x_liquid_phase',{'','sqrt(ga2x^2+ga2y^2)'}, ...
'abswLx_liquid_phase',{'','sqrt(wLx^2+wLy^2)'}, ...
'absga3x_liquid_phase',{'','sqrt(ga3x^2+ga3y^2)'}, ...
'abspLx_liquid_phase',{'','sqrt(pLx^2+pLy^2)'}, ...
'absga4x_liquid_phase',{'','sqrt(ga4x^2+ga4y^2)'}, ...
'absYLx_liquid_phase',{'','sqrt(YLx^2+YLy^2)'}, ...
'absga5x_liquid_phase',{'','sqrt(ga5x^2+ga5y^2)'}, ...
'absuVx_vapour_phase',{'sqrt(uVx^2+uVy^2)',''}, ...
'absga6x_vapour_phase',{'sqrt(ga6x^2+ga6y^2)',''}, ...
'absvVx_vapour_phase',{'sqrt(vVx^2+vVy^2)',''}, ...
'absga7x_vapour_phase',{'sqrt(ga7x^2+ga7y^2)',''}, ...
'abswVx_vapour_phase',{'sqrt(wVx^2+wVy^2)',''}, ...
'absga8x_vapour_phase',{'sqrt(ga8x^2+ga8y^2)',''}, ...
'abspVx_vapour_phase',{'sqrt(pVx^2+pVy^2)',''}, ...
'absga9x_vapour_phase',{'sqrt(ga9x^2+ga9y^2)',''}, ...
'absYVx_vapour_phase',{'sqrt(YVx^2+YVy^2)',''}, ...
'absga10x_vapour_phase',{'sqrt(ga10x^2+ga10y^2)',''}};

% Subdomain expressions
equ.expr = {'U',{'uV','uL'}, ...
	    'V',{'vV','vL'}, ...
	    'W',{'wV','wL'}, ...
	    'taux',{'muV*(uVy+vVx)','muL*(uLy+vLx)'}, ...
	    'tauy',{'2*muV*vVy','2*muL*vLy'}, ...
	    'tauz',{'muV*wVy','muL*wLy'}, ...
	    'P',{'pV','pL'}, ...
	    'Y',{'YV','YL'}, ...
	    'Ptauy',{'pV-2*muV*vVy','pL-2*muL*vLy'}, ...
	    'fy',{'-DV*YVy','-DL*YLy'}};

fem.equ = equ;

% Boundary settings
clear bnd
bnd.ind = [1,1,1,1,1,1,1,2,1,2,2,2];
bnd.dim = {'uL','vL','wL','pL','YL','uV','vV','wV','pV','YV'};
bnd.var = {};

% Boundary expressions
bnd.expr = {'tauxL',{'','muL*uLx'}, ...
	    'tauxV',{'','muV*uVy'}, ...
	    'tauyL',{'','muL*vLy'}, ...
	    'tauyV',{'','muV*vVy'}, ...
	    'tauzL',{'','muL*wLy'}, ...
	    'tauzV',{'','muv*wVy'}};

fem.bnd = bnd;

% Scalar expressions
fem.expr = {'dYBdzL','3', ...
	    'dYBdzV','-FIV/QV'};

% Coupling variable elements
clear elemcpl

% Integration coupling variables
clear elem
elem.elem = 'elcplscalar';
elem.g = {'1'};
src = cell(1,1);
clear bnd
bnd.expr = {{{},'-DV*YVy'},{{},'-DL*YLy'},{},{},{},{}};
bnd.ipoints = {{{},'4'},{{},'4'},{},{},{},{}};
bnd.frame = {{{},'xy'},{{},'xy'},{},{},{},{}};
bnd.ind = {{'1','2','3','4','5','6','7','9'},{'8','10','11','12'}};
clear equ
equ.expr = {{},{},{'wV',{}},{{},'wL'},{'wL*YL',{}},{'wV*YV',{}}};
equ.ipoints = {{},{},{'4','4'},{{},'4'},{'4','4'},{'4','4'}};
equ.frame = {{},{},{'xy','xy'},{{},'xy'},{'xy','xy'},{'xy','xy'}};
equ.ind = {{'1'},{'2'}};
src{1} = {{},bnd,equ};
elem.src = src;
geomdim = cell(1,1);
geomdim{1} = {};
elem.geomdim = geomdim;
elem.var = {'FIV','FIL','QV','QL','YWBL','YWBV'};
elem.global = {'1','2','3','4','5','6'};
elem.maxvars = {};
elemcpl{1} = elem;
fem.elemcpl = elemcpl;

% Multiphysics
fem=multiphysics(fem, ...
		 'sdl',[]);

% Initialize mesh
fem.mesh=meshinit(fem, ...
		  'hauto',5, ...
		  'hpnt',10, ...
		  'xscale',1.0, ...
		  'yscale',1.0, ...
		  'jiggle','on');

% Extend mesh
fem.xmesh=meshextend(fem,'geoms',[1],'eqvars','on','cplbndeq','on','cplbndsh','off');

% Solve problem (solves for the flow only)
fem.sol=femstatic(fem, ...
		  'solcomp',{'uL','pV','wL','wV','pL','vL','uV','vV'}, ...
		  'outcomp',{'YV','wL','uL','pV','wV','pL','vL','vV','uV','YL'});

% Save current fem structure for restart purposes
fem0=fem;

% Solve problem (Solves for the flow and compositions)
fem.sol=femstatic(fem, ...
		  'init',fem0.sol, ...
		  'solcomp',{'uL','wL','pV','YV','wV','pL','vL','uV','YL','vV'}, ...
		  'outcomp',{'uL','pV','wL','YV','wV','pL','vL','YL','vV','uV'}, ...
		  'ntol',1e-006);

% Save current fem structure for restart purposes
fem1=fem;

% Solve problem
fem.sol=femstatic(fem, ...
                  'init',fem1.sol, ...
                  'solcomp',{'vL','pV','wL','YL','uV','vV','wV','YV','pL','uL'}, ...
                  'outcomp',{'vL','pV','wL','YL','uV','vV','wV','YV','pL','uL'}, ...
                  'ntol',1e-006);


% Save current fem structure for restart purposes
fem2=fem;

% Solve problem
fem.sol=femstatic(fem, ...
                  'init',fem2.sol, ...
                  'solcomp',{'vL','pV','wL','YL','uV','vV','wV','YV','pL','uL'}, ...
                  'outcomp',{'vL','pV','wL','YL','uV','vV','wV','YV','pL','uL'}, ...
                  'ntol',1e-006);

fem3=fem
				  
% Plot solution
postplot(fem, ...
         'tridata',{'Y','cont','internal'}, ...
         'triedgestyle','none', ...
         'trifacestyle','interp', ...
         'tribar','on', ...
         'trimap','jet(1024)', ...
         'arrowdata',{'U','V'}, ...
         'arrowxspacing',20, ...
         'arrowyspacing',20, ...
         'arrowscale',0.6, ...
         'arrowtype','arrow', ...
         'arrowstyle','normalized', ...
         'arrowcolor',[1.0,1.0,1.0], ...
         'solnum','end', ...
         'phase',0, ...
         'title','Surface: uL', ...
         'refine','auto', ...
         'geom','on', ...
         'geomnum',[1], ...
         'sdl',{[1,2]}, ...
         'axisvisible','on', ...
         'axisequal','on', ...
         'grid','off', ...
         'axis',[-3.18E-4,4.41E-4,-2.69E-5,3.66E-4,-1,1]);


postplot(fem, ...
         'tridata',{'Y','cont','internal'}, ...
         'trimap','jet(1024)', ...
         'arrowdata',{'U','V'}, ...
         'arrowxspacing',20, ...
         'arrowyspacing',20, ...
         'arrowscale',0.6, ...
         'arrowtype','arrow', ...
         'arrowstyle','normalized', ...
         'arrowcolor',[1.0,1.0,1.0], ...
         'title','Surface: uL', ...
         'axis',[-1.05E-4,2.15E-4,-1.59E-5,3.36E-4]);
